language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

install:
    - composer install --dev --no-interaction --prefer-source

script:
    - vendor/bin/phpunit -c phpunit.xml.dist --testsuite unit
